yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LogoutView, LoginView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordChangeView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                       PasswordChangeDoneView)

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('user/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=10, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']
        labels = {
            'text': _('Текст поста'),
            'group': _('Группа'),
        }
        help_texts = {
            'text': _('Текст нового поста'),
            'group': _('Группа, к которой будет относиться пост'),
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import EmailField


User = get_user_model()


class CreationForm(UserCreationForm):
    email = EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from .forms import PostForm
from .models import Post, Group, User


OUTPUT_COUNT = 10


def index(request):
    template = 'posts/index.html'

    post_list = Post.objects.all()

    paginator = Paginator(post_list, OUTPUT_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)

    post_list = group.posts.all()

    paginator = Paginator(post_list, OUTPUT_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)

    post_list = author.posts.all()

    paginator = Paginator(post_list, OUTPUT_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    count_posts = len(author.posts.all())
    context = {
        'author': author,
        'page_obj': page_obj,
        'count_posts': count_posts,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'

    post = Post.objects.get(id=post_id)
    name_post = post.text[:30]
    user = get_object_or_404(User, username=post.author)
    count_posts = len(user.posts.all())

    context = {
        'post': post,
        'name_post': name_post,
        'count_posts': count_posts,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    template = 'posts/create_post.html'
    context = {'form': form,
               'title': 'Создание поста'}

    author = request.user

    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = author
        obj.save()
        return HttpResponseRedirect(reverse('posts:profile',
                                            args=(author,)))

    context['form'] = form
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(id=post_id)
    author = get_object_or_404(User, username=post.author)
    user = request.user

    if author != user:
        return HttpResponseRedirect(reverse('posts:post_detail',
                                            args=(post_id,)))

    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, instance=post)
    context = {'form': form,
               'title': 'Изменение поста',
               'is_edit': True}

    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = user
        obj.save()
        return HttpResponseRedirect(reverse('posts:post_detail',
                                            args=(post_id,)))
    context['form'] = form
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="container">
    <h2 class="text-center">Привет, я Михутов Тимур.</h2>
    <img src="{% static 'img/milaya.jpg' %}" width="640"
         height="400" class="rounded mx-auto d-block" alt="">
    <h3 class="text-center">
      Python Backend Developer <br>
      Умею делать сайты на Django. <br>
      Мой GitHub - <a href="https://github.com/T1RuS"> https://github.com/T1RuS </a> <br>
      Мой VK - <a href="https://vk.com/t1rusx"> https://vk.com/t1rusx </a>
    </h3>
  </div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% load static %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
  <div class="container">
    <h1>Вот что я умею</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
        <li class="list-group-item">
          SQL
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
    </article>
  </div>
{% endblock %}

yatube/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>{% block title %} {% endblock %} </title>
  </head>
  <body class="bg-light d-flex flex-column min-vh-100">
    {% include 'includes/header.html' %}
    <main>
      {% block content %} {% endblock %}
    </main>
    {% include 'includes/footer.html' %}
    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

yatube/templates/includes/footer.html
{% load static %}
<footer class="mt-auto border-top text-center py-3 bg-primary text-white">
  <a href="https://github.com/T1RuS">
    <img src="{% static 'img/github.svg' %}">
  </a>
  <p>© {% now "Y" as current_year %}
    {{ year }}
    <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  {% with request.resolver_match.view_name as view_name %}
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30"
               height="30" class="rounded d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}" href="{% url 'posts:index' %}">
                Главная
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Об авторе</a>
              <div class="dropdown-menu bg-light">
                <a class="dropdown-item {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Профиль автора</a>
                <a class="dropdown-item {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
                <a class="dropdown-item" href="https://github.com/T1RuS">Git Автора</a>
                <a class="dropdown-item" href="https://vk.com/t1rusx">VK Автора</a>
              </div>
            </li>
          </ul>

          <div class="d-flex">
            {% if user.is_authenticated %}
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> {{ user.username }} </a>
                  <div class="dropdown-menu bg-light">
                    <a class="dropdown-item {% if view_name  == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
                    <a class="dropdown-item {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
                  </div>
                </li>
              </ul>
            {% else %}
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">
                    Войти
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">
                    Зарегистрироваться
                  </a>
                </li>
              </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  {% endwith %}
</header>

yatube/templates/includes/posts.html
<div class="card bg-light mb-3">
  <article>
    <ul class="card-header list-unstyled">
      <li>
        Автор: <a class="btn-link" href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <div class="card-body">
    {% load user_filters %}
      <p>{{ post.text }}</p>
      <a class="btn btn-secondary" href="{% url "posts:post_detail" post.id %}">Подробная информация </a>
      {% if post.group %}
        <a class="btn btn-secondary" href="{% url 'posts:group_list' post.group.slug %}">
          Все записи группы: {{post.group.title}}</a>
      {% endif %}
      {% if post.author|lower == user.username|lower %}
        <a class="btn btn-secondary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать пост </a>
      {% endif %}
    </div>
  </article>
</div>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% load user_filters %}
{% block content %}
  <div class="container py-3">
    <div class="row justify-content-center">
      <div class="col-md-8 p-3">
        <div class="card">
          <div class="card-header">
              {{title}}
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <div class="form-group row my-2 p-2">
                <label for="id_text">
                  {{ form.text.label }}
                  <span class="required text-danger" >*</span>
                </label>
                {{ form.text|addclass:"form-control"}}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.text.help_text }}
                </small>
              </div>
              <div class="form-group row my-2 p-2">
                <label for="id_group">
                  {{ form.group.label }}
                </label>
                      {{ form.group|addclass:"form-control"}}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
              <div class="text-center">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %} Записи сообщества {{ group }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p> {{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'includes/posts.html' %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation navbar-dark" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            &laquo;
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
       {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            &raquo;
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %} Последние обновления на сайте {% endblock %}

{% block content %}
  <div class="container py-5">
    <h2>Последние обновления на сайте</h2>
    {% for post in page_obj %}
      {% include 'includes/posts.html' %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} Пост {{ name_post }} {% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="card bg-light mb-3">
      <article>
        <ul class="card-header list-unstyled">
          <li>
            Автор: <a class="btn-link" href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
          </li>
          <li>
              Всего постов автора: {{ count_posts }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <div class="card-body">
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a class="btn btn-secondary" href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы: {{post.group.title}}</a>
          {% endif %}
        </div>
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}

{% block content %}
  <div class="container py-5">
    <h4>Все посты пользователя: {{ author.get_full_name }} </h4>
    <h4>Всего постов: {{ count_posts }} </h4>

    {% for post in page_obj %}
      {% include 'includes/posts.html' %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9 col-lg-7 col-xl-6 col-xxl-5 p-3">
      <div class="card">
        <div class="card-header text-center">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body">
            <p>Пароль изменён успешно</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-9 col-lg-7 col-xl-6 col-xxl-5 p-3">
        <div class="card">
          <div class="card-header text-center">Зарегистрироваться</div>
            <div class="card-body">
              {% load user_filters %}
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group my-1">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control'}}
                      {% if field.help_text %}
                        <small
                           id="{{ field.id_for_label }}-help"
                           class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %} 